In [1]:
import torch

In [2]:
import numpy as np

In [15]:
array = np.arange(6.); print(array)

[0. 1. 2. 3. 4. 5.]


In [16]:
t1 = torch.Tensor(array); print(t1)

tensor([0., 1., 2., 3., 4., 5.])


In [17]:
t2 = torch.tensor(array); print(t2)

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


In [18]:
t3 = torch.as_tensor(array); print(t3)

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


In [19]:
t4 = torch.from_numpy(array); print(t4)

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


In [22]:
array.reshape(1,-1)#.squeeze()

array([[0., 1., 2., 3., 4., 5.]])

In [23]:
array.reshape(1,-1).squeeze()

array([0., 1., 2., 3., 4., 5.])

In [26]:
next(iter([1,23,3]))

1

In [29]:
next(iter(array))

0.0

In [30]:
next(iter(array))

0.0

In [4]:
x =torch.randn(5, 5) #requires_grad = False by defaults
y =torch.randn(5, 5) #requires_grad = False by defaults
z =torch.randn((5, 5), requires_grad=True)
a = x + y
b = a + z

In [5]:
print(a,b)

tensor([[ 0.8252, -1.8375,  1.2509, -0.6841,  1.4015],
        [ 1.6767,  3.2892, -1.6789,  0.1469, -0.1271],
        [-1.3656, -3.4695, -1.9617,  1.9795, -1.2266],
        [ 0.5148, -1.3932,  2.6723, -0.6981, -0.7784],
        [ 0.4303,  0.1197,  0.4003,  1.2986, -0.7982]]) tensor([[-0.6632, -1.5923,  0.3492, -0.7401,  1.3526],
        [ 2.9655,  3.9204, -2.7321,  1.1715,  0.9575],
        [-1.4007, -2.7489, -2.0351,  1.6405, -0.4578],
        [ 0.8896, -0.6937,  0.9534, -0.9360, -1.2110],
        [ 0.9579, -0.9982,  0.0474,  1.9790, -2.8920]], grad_fn=<AddBackward0>)


In [3]:
import torch

In [8]:
t = torch.tensor([1,2,3])


In [10]:
t.max()

tensor(3)

In [11]:
t = torch.tensor([
    [1, 0, 0, 2],
    [0, 3, 3, 0],
    [4, 0, 0, 5]
], dtype=torch.float32)

In [13]:
t.max(dim=0) 

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))