In [1]:
import torch

In [2]:
import numpy as np

In [15]:
array = np.arange(6.); print(array)

[0. 1. 2. 3. 4. 5.]


In [16]:
t1 = torch.Tensor(array); print(t1)

tensor([0., 1., 2., 3., 4., 5.])


In [17]:
t2 = torch.tensor(array); print(t2)

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


In [18]:
t3 = torch.as_tensor(array); print(t3)

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


In [19]:
t4 = torch.from_numpy(array); print(t4)

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


In [22]:
array.reshape(1,-1)#.squeeze()

array([[0., 1., 2., 3., 4., 5.]])

In [23]:
array.reshape(1,-1).squeeze()

array([0., 1., 2., 3., 4., 5.])

In [26]:
next(iter([1,23,3]))

1

In [29]:
next(iter(array))

0.0

In [30]:
next(iter(array))

0.0